# Generated by Django 4.0.4 on 2022-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=200)),
                ('developer_name', models.CharField(max_length=200)),
            ],
        ),
    ]
