# Generated by Django 4.0.4 on 2022-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_brand', models.CharField(max_length=50)),
                ('car_price', models.IntegerField()),
            ],
        ),
    ]
