# Generated by Django 4.0.4 on 2022-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('cricketer_age', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('batting_avg', models.IntegerField()),
            ],
        ),
    ]
