# Generated by Django 4.0.4 on 2022-04-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
            ],
        ),
    ]
