# Generated by Django 4.0.4 on 2022-04-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField()),
                ('Employee_name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
